src/Website/Areas/Mijn/Models/SerieViewModels.cs
using System.Collections.Generic;
using Data.Tables;

namespace Prekenweb.Website.Areas.Mijn.Models
{
    public class SerieIndexViewModel
    {
        public List<Serie> Series { get; set; }
    }
    public class SerieEditViewModel
    {
        public Serie Serie { get; set; }
    }
}

src/Website/Areas/Mijn/Controllers/SerieController.cs
using Prekenweb.Website.Areas.Mijn.Models;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Data;
using Data.Identity;
using Data.Tables;
using Prekenweb.Website.Lib;

namespace Prekenweb.Website.Areas.Mijn.Controllers
{
    [Authorize(Roles = "Stamgegevens")]
    public class SerieController : Controller
    {
        private readonly IPrekenwebContext<Gebruiker> _context;

        public SerieController(IPrekenwebContext<Gebruiker> context)
        {
            _context = context;
        } 

        public ActionResult Index()
        {
            var taalId = TaalInfoHelper.FromRouteData(RouteData).Id;
            return View(new SerieIndexViewModel
            {
                Series = _context.Series.Where(s => s.TaalId == taalId).OrderBy(s => s.Omschrijving).ToList()
            });
        }

        public ActionResult Verwijder(int id)
        {
            var serie = _context.Series.Single(s => s.Id == id);
            _context.Series.Remove(serie);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Bewerk(int id)
        {
            var serie = _context.Series.Single(s => s.Id == id);
            return View(new SerieEditViewModel
            {
                Serie = serie
            });
        }

        [HttpPost]
        public ActionResult Bewerk(SerieEditViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);

            _context.Entry(viewModel.Serie).State = EntityState.Modified;
            _context.SaveChanges();
            
            return View(viewModel);
        }

        public ActionResult Maak()
        {
            return View(new SerieEditViewModel
            {
                Serie = new Serie { TaalId = TaalInfoHelper.FromRouteData(RouteData).Id }
            });
        }

        [HttpPost]
        public ActionResult Maak(SerieEditViewModel viewModel)
        {
            if (!ModelState.IsValid) return View(viewModel);
            
            _context.Series.Add(viewModel.Serie);
            _context.SaveChanges();
            
            return RedirectToAction("Bewerk", new { viewModel.Serie.Id });
        }
    }
}

src/Website/Areas/Mijn/Views/Serie/Bewerk.cshtml
@model SerieEditViewModel
@{ ViewBag.Title = string.Format("{0} {1} {2}", Resources.Bewerk, Resources.Serie.ToLower(), Model.Serie.Omschrijving); }

<h1>@ViewBag.Title</h1>
@using (Html.BeginForm("Bewerk", "Serie", FormMethod.Post, new { name = "FormSerie" }))
{
    @Html.HiddenFor(m => m.Serie.Id)
    @Html.HiddenFor(m => m.Serie.OudId)
    @Html.HiddenFor(m => m.Serie.TaalId)
    @Html.Partial("MaakBewerk", Model)
    <p class="clear"></p>
    <a href="@Url.Action("Index")" class="IconKnop">
        <div class="fa fa-arrow-left"></div>
        @Resources.Terug</a>
    <a href="#" onclick="document.FormSerie.submit(); return false;" class="IconKnop">
        <div class="fa fa-save"></div>
        @Resources.Opslaan</a>
 
    <p class="clear"></p>
}

src/Website/Areas/Mijn/Views/Serie/Index.cshtml
@model SerieIndexViewModel
@{ ViewBag.Title = Resources.Series; }

<h1>@ViewBag.Title</h1>
<div id="grid">
    @{
        WebGrid wb = new WebGrid(Model.Series, new string[] { "Omschrijving", "Taal.Omschrijving", "Id" }, rowsPerPage: 30);
        @wb.GetHtml(
            columns:
                wb.Columns(
                    wb.Column(columnName: "Id"),
                    wb.Column(columnName: "Omschrijving", header: Resources.Omschrijving), 
                    wb.Column("Bewerk", " ", format: (item) => { return Html.ActionLink(Resources.Bewerk, "Bewerk", new { Id = item.Id }, new { }); }),
                    wb.Column("Verwijder", " ", format: (item) => { return Html.ActionLink(Resources.Verwijder, "Verwijder", new { Id = item.Id }, new { OnClick = "return(confirm('Verwijderen, zeker weten?'))" }); })
                )
            );
    }
</div> 
<a href="@Url.Action("Maak")" class="IconKnop">
    <div class="fa fa-file"></div>
    @Resources.NieuweSerie</a><br />
<br />

src/Website/Areas/Mijn/Views/Serie/Maak.cshtml
@model SerieEditViewModel
@{ ViewBag.Title = "Maak serie"; }

<h1>@ViewBag.Title</h1>
@using (Html.BeginForm("Maak", "Serie", FormMethod.Post, new { name = "FormSerie" }))
{
    @Html.HiddenFor(m => m.Serie.TaalId)
    @Html.Partial("MaakBewerk", Model)
    <p class="clear"></p>
    <a href="@Url.Action("Index")" class="IconKnop">
        <div class="fa fa-arrow-left"></div>
        @Resources.Terug</a>
    <a href="#" onclick="document.FormSerie.submit(); return false;" class="IconKnop">
        <div class="fa fa-save"></div>
        @Resources.Aanmaken</a>
 
    <p class="clear"></p>
}

src/Website/Areas/Mijn/Views/Serie/MaakBewerk.cshtml
@model SerieEditViewModel
@Html.ValidationSummary(true)
<div class="ColumnM">
    <div class="field">
        <div class="label">@Html.LabelFor(m => m.Serie.Omschrijving)</div>
        <div class="value">@Html.EditorFor(m => m.Serie.Omschrijving)</div>
        <div class="validator">@Html.ValidationMessageFor(m => m.Serie.Omschrijving)</div>
    </div> 
</div>