src/Website/Areas/Mijn/Models/PreekViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Data.Tables;

namespace Prekenweb.Website.Areas.Mijn.Models
{
    public class PreekNogTePublicerenViewModel
    {
        public List<Preek> Preken { get; set; }
        public int? FromPreekId { get; set; }
    }
    public class KiesVers
    {
        public string Veldnaam { get; set; }

        [Display(Name = "Boek", ResourceType = typeof(Resources.Resources))]
        public string Boek { get; set; }

        [Display(Name = "Hoofdstuk", ResourceType = typeof(Resources.Resources))]
        public int? Hoofdstuk { get; set; }

        public IQueryable<BoekHoofdstukTekst> Teksten { get; set; }
    }
}

src/Website/Areas/Mijn/Controllers/PreekController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Azure.Storage.Blobs;
using Data;
using Data.Identity;
using Data.Tables;
using Data.ViewModels;
using Hangfire;
using Prekenweb.Website.Areas.Mijn.Models;
using Prekenweb.Website.Lib;
using Prekenweb.Website.Lib.Hangfire;
using PrekenWeb.Security;
using TweetSharp;

namespace Prekenweb.Website.Areas.Mijn.Controllers
{
    [Authorize]
    public class PreekController : Controller
    {
        private readonly IPrekenwebContext<Gebruiker> _context;
        private readonly IHuidigeGebruiker _huidigeGebruiker;
        private readonly IPrekenWebUserManager _prekenWebUserManager;

        public PreekController(IPrekenwebContext<Gebruiker> context,
            IHuidigeGebruiker huidigeGebruiker,
            IPrekenWebUserManager prekenWebUserManager)
        {
            _context = context;
            _huidigeGebruiker = huidigeGebruiker;
            _prekenWebUserManager = prekenWebUserManager;
        }

        #region Bewerk
        [Authorize(Roles = "PreekToevoegen")]
        public async Task<ViewResult> Bewerk(int id)
        {
            var preek = _context.Preeks.Single(p => p.Id == id);

            if (!User.IsInRole("PrekenVanAnderenBewerken") && preek.AangemaaktDoor != await _huidigeGebruiker.GetId(_prekenWebUserManager, User)) throw new UnauthorizedAccessException("Cannot edit someone else's sermon");

            //preek.Gepubliceerd = User.IsInRole("PreekFiatteren");
            preek.DatumBijgewerkt = DateTime.Now;

            return View(preek);
        }

        [HttpPost, Authorize(Roles = "PreekToevoegen"), ValidateInput(false)]
        public async Task<ActionResult> Bewerk(Preek viewModel, HttpPostedFileBase bestand, HttpPostedFileBase source)
        {
            if (viewModel.Gepubliceerd)
            {
                if (!viewModel.DatumGepubliceerd.HasValue && !User.IsInRole("PreekFiatteren"))
                {
                    ModelState.AddModelError("Gepubliceerd", @"Onvoldoende rechten");
                }
            }
            else
            {
                viewModel.DatumGepubliceerd = null;
            }

            if (!ModelState.IsValid) return View(viewModel);

            _context.Entry(viewModel).State = EntityState.Modified;
            LezenEnZingenBijwerken(viewModel);
            _context.SaveChanges();

            var preek = _context.Preeks.Include(x => x.Predikant).Single(p => p.Id == viewModel.Id);

            if (viewModel.Gepubliceerd && !viewModel.DatumGepubliceerd.HasValue)
            {
                this.TweetNieuwePreek(preek);
                viewModel.DatumGepubliceerd = DateTime.Now;
            }

            try
            {
                viewModel.Bestandsnaam = BlobStorageHelper.HandleSermonUpload(bestand, viewModel.Id, ConfigurationManager.AppSettings["PrekenFolder"], viewModel.Bestandsnaam);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(viewModel);
            }

            try
            {
                if (source != null)
                    viewModel.SourceFileName = BlobStorageHelper.HandleSermonUpload(source, viewModel.Id, ConfigurationManager.AppSettings["LectureSourcesFolder"], source.FileName);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(viewModel);
            }

            preek.DatumBijgewerkt = DateTime.Now;
            preek.AangepastDoor = await _huidigeGebruiker.GetId(_prekenWebUserManager, User);

            OutputCacheHelpers.ClearOutputCaches(Response, Url);
            _context.SaveChanges();

            BackgroundJob.Enqueue<AchtergrondTaken>(x => x.AnalyseerAudioTaak(preek.Id));

            if (ModelState.IsValid) return RedirectToAction("NogTePubliceren", new { fromPreekId = preek.Id });

            return View(preek);
        }

        #endregion

        #region Maak
        [Authorize(Roles = "PreekToevoegen")]
        public ActionResult Maak()
        {
            return View(new Preek
            {
                DatumAangemaakt = DateTime.Now,
                DatumBijgewerkt = DateTime.Now,
                Gepubliceerd = User.IsInRole("PreekFiatteren"),
                PreekTypeId = (int)PreekTypeEnum.Preek,
                TaalId = TaalInfoHelper.FromRouteData(RouteData).Id,
                PreekLezenEnZingens = new List<PreekLezenEnZingen>
                {
                    new PreekLezenEnZingen { Soort = Resources.Resources.Zingen, Sortering= 1 },
                    new PreekLezenEnZingen { Soort = Resources.Resources.Lezen, Sortering= 2 },
                    new PreekLezenEnZingen { Soort = Resources.Resources.Zingen, Sortering= 3 },
                    new PreekLezenEnZingen { Soort = Resources.Resources.Zingen, Sortering= 4 },
                    new PreekLezenEnZingen { Soort = Resources.Resources.Zingen, Sortering= 5 },
                }
            });
        }

        [Authorize(Roles = "PreekToevoegen"), HttpPost, ValidateInput(false)]
        public async Task<ActionResult> Maak(Preek viewModel, HttpPostedFileBase bestand, HttpPostedFileBase source)
        {
            if (viewModel.Gepubliceerd)
            {
                if (!viewModel.DatumGepubliceerd.HasValue && !User.IsInRole("PreekFiatteren"))
                {
                    ModelState.AddModelError("Gepubliceerd", @"Onvoldoende rechten");
                }
            }
            else
            {
                viewModel.DatumGepubliceerd = null;
            }

            if (ModelState.IsValid)
            {
                _context.Preeks.Add(viewModel);
                LezenEnZingenBijwerken(viewModel);
                _context.SaveChanges();

                var preek = _context.Preeks.Include(x => x.Predikant).Single(p => p.Id == viewModel.Id);

                if (viewModel.Gepubliceerd && !viewModel.DatumGepubliceerd.HasValue)
                {
                    this.TweetNieuwePreek(preek);
                    viewModel.DatumGepubliceerd = DateTime.Now;
                }

                try
                {
                    if (bestand != null)
                        viewModel.Bestandsnaam = BlobStorageHelper.HandleSermonUpload(bestand, preek.Id, ConfigurationManager.AppSettings["PrekenFolder"], bestand.FileName);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(viewModel);
                }

                try
                {
                    if (source != null)
                        viewModel.SourceFileName = BlobStorageHelper.HandleSermonUpload(source, preek.Id, ConfigurationManager.AppSettings["LectureSourcesFolder"], source.FileName);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(viewModel);
                }

                preek.DatumBijgewerkt = DateTime.Now;
                preek.AangemaaktDoor = await _huidigeGebruiker.GetId(_prekenWebUserManager, User);

                OutputCacheHelpers.ClearOutputCaches(Response, Url);
                _context.SaveChanges();

                BackgroundJob.Enqueue<AchtergrondTaken>(x => x.AnalyseerAudioTaak(preek.Id));

                if (ModelState.IsValid) return RedirectToAction("NogTePubliceren", new { fromPreekId = preek.Id });

                return View(preek);
            }

            if (bestand != null) ModelState.AddModelError("", @"Let op, er waren fouten, corrigeer deze maar kies ook opnieuw het bestand want deze is nog niet opgeslagen en wordt ook niet onthouden");

            return View(viewModel);
        }

        private void TweetNieuwePreek(Preek preekModel)
        {
            try
            {
                if (TaalInfoHelper.FromRouteData(RouteData).Naam != "nl")
                {
                    return;
                }

                var customerKey = ConfigurationManager.AppSettings["TwitterCustomerKey"];
                var customerSecret = ConfigurationManager.AppSettings["TwitterCustomerSecret"];
                var token = ConfigurationManager.AppSettings["TwitterToken"];
                var tokenSecret = ConfigurationManager.AppSettings["TwitterTokenSecret"];

                // Fix om de connectie met twitter via TLS1.1 of TLS1.2 te laten lopen, via SSL3 gaat het niet goed.
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
                var service = new TwitterService(customerKey, customerSecret, token, tokenSecret);
                var url = Url.Action("Open", null, new { preekModel.Id }, Request.Url.Scheme).Replace("/Mijn", string.Empty); ;
                var preekType = (PreekTypeEnum)preekModel.PreekTypeId;
                var statusUpdate = $"Een nieuwe {preekType.ToString().ToLower()} van {preekModel.Predikant.VolledigeNaam}: {url}";
                service.SendTweet(new SendTweetOptions { Status = statusUpdate });
            }
            catch
            {
            }
        }

        private void LezenEnZingenBijwerken(Preek viewModel)
        {
            _context.PreekLezenEnZingens.Where(plz => plz.PreekId == viewModel.Id).ToList().ForEach(plz => _context.PreekLezenEnZingens.Remove(plz));
            if (viewModel.PreekTypeId != (int)PreekTypeEnum.LeesPreek) return;

            byte index = 1;

src/Website/Areas/Mijn/Views/Preek/Bewerk.cshtml
@model Data.Tables.Preek
@{ ViewBag.Title = Resources.BewerkPreek; }
<h1>@ViewBag.Title</h1>
@using (Html.BeginForm("Bewerk", "Preek", FormMethod.Post, new { name = "FormPreek", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.AantalKeerGedownload)
    @Html.HiddenFor(m => m.Bestandsnaam)
    @Html.HiddenFor(m => m.Bestandsgrootte)
    @Html.HiddenFor(m => m.Duur)
    @Html.HiddenFor(m => m.OudId)
    @Html.HiddenFor(m => m.TaalId)
    @Html.HiddenFor(m => m.VanVers)
    @Html.HiddenFor(m => m.TotVers)
    @Html.HiddenFor(m => m.AangepastDoor)
    @Html.HiddenFor(m => m.AangemaaktDoor)
    @Html.Partial("MaakBewerk", Model)
    <p class="clear"></p>
    <div class="FormKnoppen">
        <a href="@Url.Action("Index", "Home")" class="IconKnop">
            <div class="fa fa-arrow-left"></div>
            @Resources.Terug
        </a>
        <a href="#" onclick="$('.tabs').hide(); $('.FormKnoppen').hide(); $('.validation-summary-errors').hide(); $('.Loading').show(); document.FormPreek.submit(); return false;" class="IconKnop">
            <div class="fa fa-save"></div>
            @Resources.Opslaan
        </a>
        <a href="@Url.Action("Verwijder", "Preek", new { id = Model.Id })" class="IconKnop" onclick="return confirm('Zeker weten dat u deze preek wilt verwijderen?')">
            <div class="fa fa-trash"></div>
            @Resources.Verwijder
        </a>
    </div>
    <p class="clear"></p>
}
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            prekenweb.automatischeTekstenChanged();
        });
    </script>
}

src/Website/Areas/Mijn/Views/Preek/KiesVers.cshtml
@using Prekenweb.Website.Lib.HtmlHelpers
@model KiesVers
@{
    ViewBag.Title = Resources.Kies;
}
<div id="ZoekVersContainer">
    <script type="text/javascript">
        function KiesVers(id, omschrijving) {
            var label = document.getElementById("@string.Format("{0}_display", Model.Veldnaam)");
            var input = document.getElementById("@string.Format("{0}", Model.Veldnaam)");
            label.innerHTML = omschrijving;
            input.value = id;
            $('.prekenwebPopup').dialog('destroy').remove();
            prekenweb.updateAutomatischeBijbeltekst();
        }
    </script>
    <h1>@ViewBag.Title</h1>
    @using (Ajax.BeginForm("KiesVers", "Preek", new AjaxOptions { UpdateTargetId = "ZoekVersContainer" }, new { name = "FormZoekPreek" }))
    {
        @Html.HiddenFor(x => x.Veldnaam)
        <div class="ColumnM">
            <div class="field">
                <div class="label">@Html.LabelFor(m => m.Boek)</div>
                <div class="value">@Html.EditorFor(m => m.Boek, new { data_autocomplete_type = "Boek" })</div>
                <div class="tooltip">@Html.ToolTipFor(m => m.Boek)</div>
                <div class="validator">@Html.ValidationMessageFor(m => m.Boek)</div>
            </div>
            <div class="field">
                <div class="label">@Html.LabelFor(m => m.Hoofdstuk)</div>
                <div class="value">@Html.EditorFor(m => m.Hoofdstuk)</div>
                <div class="tooltip">@Html.ToolTipFor(m => m.Hoofdstuk)</div>
                <div class="validator">@Html.ValidationMessageFor(m => m.Hoofdstuk)</div>
            </div>
        </div>
        <p class="clear"></p>
        <input type="submit" class="Knop" value="@Resources.Zoek" />
        <p class="clear"></p>

    }
    <div id="grid">
        @{
            WebGrid wb = new WebGrid(Model.Teksten, new string[] { "BoekHoofdstuk.Omschrijving", "Id", "Hoofdstuk", "Vers" }, rowsPerPage: 200);
            @wb.GetHtml(
            columns:
                wb.Columns(
                    //wb.Column(columnName: "Id"),
                    wb.Column(columnName: "BoekHoofdstuk.Omschrijving", header: Resources.Boek),
                    wb.Column(columnName: "Hoofdstuk", header: Resources.Hoofdstuk),
                    wb.Column(columnName: "Vers", header: Resources.Vers),
                    wb.Column(columnName: "Tekst", header: Resources.Tekst, format: (item) => { return item.Tekst == null ? "" : ((string)item.Tekst).Length > 100 ? ((string)item.Tekst).Substring(0, 100) + "..." : item.Tekst; }),
                    wb.Column("Kies", " ", format: (item) => { return Html.ActionLink(Resources.Kies, "Kies", new { Id = item.Id }, new { OnClick = "KiesVers(" + item.Id + ",'" + item.Omschrijving + "'); return false;" }); })
                )
            );
        }
    </div>
</div> 

src/Website/Areas/Mijn/Views/Preek/Maak.cshtml
@model Data.Tables.Preek
@{ ViewBag.Title = Resources.UploadEenNieuwePreek; }
<h1>@ViewBag.Title</h1>
@using (Html.BeginForm("Maak", "Preek", FormMethod.Post, new { name = "FormPreek", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.TaalId)
    @Html.HiddenFor(m => m.AangemaaktDoor)
    @Html.Partial("MaakBewerk", Model)

    <p class="clear"></p>
    <div class="FormKnoppen">
        <a href="@Url.Action("Index", "Home")" class="IconKnop">
            <div class="fa fa-arrow-left"></div>
            @Resources.Terug
        </a>
        <a href="#" onclick="$('.tabs').hide(); $('.FormKnoppen').hide(); $('.validation-summary-errors').hide(); $('.Loading').show(); document.FormPreek.submit(); return false;" class="IconKnop">
            <div class="fa fa-file"></div>
            @Resources.Aanmaken
        </a>
        <a href="http://youtu.be/FpGCy-Inf-Y" class="IconKnop" target="_blank">
            <div class="fa fa-youtube-play"></div>
            @Resources.Instructievideo
        </a>
    </div>
    <p class="clear"></p>
}
@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            prekenweb.automatischeTekstenChanged();
        });
     </script>
}

src/Website/Areas/Mijn/Views/Preek/NogTePubliceren.cshtml
@model PreekNogTePublicerenViewModel
@{ ViewBag.Title = Resources.OngepubliceerdePreken; }

<h1>@ViewBag.Title</h1>
@if (Model.FromPreekId.HasValue)
{
    <div style="border:1px solid green; border-radius:3px; background-color:white; padding:20px; margin-bottom:20px; text-align:center;">
        @Html.ActionLink(Resources.PreekOpgeslagen, "Bewerk", "Preek", new { Id = Model.FromPreekId.Value }, new { })
    </div>
}
<div id="grid">
    @{
        if (!Model.Preken.Any())
        {
            <p>@Resources.AllLecturesHaveBeenPublished</p>
        }
        else
        {
            WebGrid wb = new WebGrid(Model.Preken, new string[] { "Predikant.Achternaam", "AangepastGebruikerNaam", "AangemaaktGebruikerNaam", "DatumAangemaakt", "Boekhoofdstuk.Omschrijving", "Id", "Hoofdstuk" }, rowsPerPage: 30);
            @wb.GetHtml(
                columns:
                    wb.Columns(
                        wb.Column(columnName: "Id"),
                        wb.Column(columnName: "AangemaaktGebruikerNaam", header: Resources.AangemaaktDoor),
                        wb.Column(columnName: "AangepastGebruikerNaam", header: Resources.AangepastDoor),
                        wb.Column(columnName: "GebeurtenisTekst", header: Resources.Gebeurtenis),
                        wb.Column(columnName: "Predikant.Achternaam", header: Resources.Predikant),
                        wb.Column(columnName: "DatumAangemaakt", header: Resources.AangemaaktOp),
                        wb.Column(columnName: "BoekTekst", header: Resources.Boek),
                        wb.Column(columnName: "Hoofdstuk", header: Resources.Hoofdstuk),
                        wb.Column("Bewerk", " ", format: (item) => { return Html.ActionLink("Open", "Bewerk", new { Id = item.Id }, new { }); })
                    )
                );
        }
    }
</div>