src/Website/Areas/Mijn/Models/Afbeelding.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;
using Data.Tables;

namespace Prekenweb.Website.Areas.Mijn.Models
{
    public class AfbeeldingIndexViewModel
    {
        public List<Afbeelding> Afbeeldingen { get; set; }
    }
    public class AfbeeldingEditViewModel
    {
        public Afbeelding Afbeelding { get; set; }

        [NotMapped, DisplayName("Bestand"), DataType(DataType.Upload)]
        public HttpPostedFileBase Bestand { get; set; }
    }
}

src/Website/Areas/Mijn/Controllers/AfbeeldingController.cs
using System.Configuration;
using Prekenweb.Website.Areas.Mijn.Models;
using System;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Data;
using Data.Identity;
using Data.Tables;
using Prekenweb.Website.Lib;
using System.Runtime.InteropServices.ComTypes;

namespace Prekenweb.Website.Areas.Mijn.Controllers
{
    [Authorize(Roles = "Spotlight")]
    public class AfbeeldingController : Controller
    {
        private readonly IPrekenwebContext<Gebruiker> _context;

        public AfbeeldingController(IPrekenwebContext<Gebruiker> context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            return View(new AfbeeldingIndexViewModel
            {
                Afbeeldingen = _context.Afbeeldings.OrderByDescending(g => g.Id).ToList()
            });
        }

        public ActionResult Verwijder(int id)
        {
            Afbeelding afbeelding = _context.Afbeeldings.Single(a => a.Id == id);
            var rootFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];

            BlobStorageHelper.DeleteIfExists(Path.Combine(rootFolder, afbeelding.Bestandsnaam));
            BlobStorageHelper.DeleteIfExists(Path.Combine(rootFolder, $"Thumbnail_{afbeelding.Id}.jpg"));
            BlobStorageHelper.DeleteIfExists(Path.Combine(rootFolder, $"Homepage_{afbeelding.Id}.jpg"));

            OutputCacheHelpers.ClearOutputCaches(Response, Url);

            _context.Afbeeldings.Remove(afbeelding);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Bewerk(int id)
        {
            Afbeelding afbeelding = _context.Afbeeldings.Single(a => a.Id == id);
            ViewBag.AfbeeldingenFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];
            return View(new AfbeeldingEditViewModel
            {
                Afbeelding = afbeelding
            });
        }

        [HttpPost]
        public ActionResult Bewerk(AfbeeldingEditViewModel viewModel)
        {
            ViewBag.AfbeeldingenFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];
          
            if (!ModelState.IsValid) return View(viewModel);

            _context.Entry(viewModel.Afbeelding).State = EntityState.Modified;
            _context.SaveChanges();

            ModelState.Clear();

            string geuploadeAfbeeldingLocatie;

            try
            {
                geuploadeAfbeeldingLocatie = HandleUpload(viewModel.Bestand, viewModel.Afbeelding);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Bestand", ex.Message);
                return View(viewModel);
            }

            var afbeelding = _context.Afbeeldings.Single(a => a.Id == viewModel.Afbeelding.Id);

            if (!string.IsNullOrEmpty(geuploadeAfbeeldingLocatie))
            {
                HandleImage(geuploadeAfbeeldingLocatie, afbeelding.Id, false);
                if (!ModelState.IsValid) return View(viewModel);
            }

            OutputCacheHelpers.ClearOutputCaches(Response, Url);

            return View(new AfbeeldingEditViewModel
            {
                Afbeelding = afbeelding
            });
        }

        public void HandleImage(string geuploadeAfbeeldingLocatie, int afbeeldingId, bool isNieuw)
        {
            using (var image = GetImage(geuploadeAfbeeldingLocatie))
            {
                try
                {
                    if (image.Height >= 340 && image.Width >= 1024)
                    {
                        MaakHomepageImage(image, afbeeldingId);
                    }

                    MaakThumbnailImage(image, afbeeldingId);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Bestand", ex.Message);
                }
            }
        }

        public ActionResult Maak()
        {
            ViewBag.AfbeeldingenFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];
            return View(new AfbeeldingEditViewModel
            {
                Afbeelding = new Afbeelding()
            });
        }

        [HttpPost]
        public ActionResult Maak(AfbeeldingEditViewModel viewModel)
        {
            if (viewModel.Bestand == null || !(viewModel.Bestand.ContentLength > 0)) ModelState.AddModelError("Bestand", "Geen bestand gekozen");

            ViewBag.AfbeeldingenFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];

            if (!ModelState.IsValid || viewModel.Bestand == null) return View(viewModel);
            
            viewModel.Afbeelding.Bestandsnaam = viewModel.Bestand.FileName;
            viewModel.Afbeelding.ContentType = viewModel.Bestand.ContentType;
            _context.Afbeeldings.Add(viewModel.Afbeelding);
            _context.SaveChanges();

            ModelState.Clear();

            OutputCacheHelpers.ClearOutputCaches(Response, Url);

            string geuploadeAfbeeldingLocatie;

            try
            {
                geuploadeAfbeeldingLocatie = HandleUpload(viewModel.Bestand, viewModel.Afbeelding);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Bestand", ex.Message);
                return View(viewModel);
            }

            var afbeelding = _context.Afbeeldings.Single(a => a.Id == viewModel.Afbeelding.Id);

            if (!string.IsNullOrEmpty(geuploadeAfbeeldingLocatie))
            {
                HandleImage(geuploadeAfbeeldingLocatie, afbeelding.Id, true);
                if (!ModelState.IsValid) return View(viewModel);
            }
            else
            {
                ModelState.AddModelError("Bestand", "Geen afbeelding geupload, afbeelding aangemaakt maar zonden bestand!");
                return View(viewModel);
            }

            return RedirectToAction("Bewerk", new { viewModel.Afbeelding.Id });
        }

        public Image GetImage(string geuploadeAfbeeldingLocatie)
        {
            using (var memorystream = new MemoryStream())
            {
                BlobStorageHelper.Stream(geuploadeAfbeeldingLocatie, memorystream);
                return Image.FromStream(memorystream);
            }
        }

        public void MaakThumbnailImage(Image origineel, int afbeeldingId)
        {
            var rootFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];
            var thumbnailBestandsnaam = Path.Combine(rootFolder, $"Thumbnail_{afbeeldingId}.jpg");

            using (var newImage = new Bitmap(100, 100))
            using (var graphics = Graphics.FromImage(newImage))
            {
                graphics.SmoothingMode = SmoothingMode.AntiAlias;
                graphics.InterpolationMode = InterpolationMode.NearestNeighbor;
                graphics.PixelOffsetMode = PixelOffsetMode.HighSpeed;
                graphics.DrawImage(origineel, new Rectangle(0, 0, 100, 100));
                if (BlobStorageHelper.Exists(thumbnailBestandsnaam))
                {
                    BlobStorageHelper.DeleteIfExists(thumbnailBestandsnaam);
                }
                using (var memorystream = new MemoryStream())
                {
                    newImage.Save(memorystream, ImageFormat.Jpeg);
                    // Reset the stream position to the beginning
                    memorystream.Seek(0, SeekOrigin.Begin);
                    BlobStorageHelper.Upload(memorystream, thumbnailBestandsnaam);
                }
            }
        }

        public void MaakHomepageImage(Image origineel, int afbeeldingId)
        {
            var rootFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];
            var thumbnailBestandsnaam = Path.Combine(rootFolder, $"Homepage_{afbeeldingId}.jpg");
            double height = 340.0;
            double width = origineel.Width;

            width = (height / origineel.Height) * width;

            if (width < 1024.0)
            {
                width = 1024.0;
                height = (1024.0 / origineel.Width) * origineel.Height;
            }

            using (var newImage = new Bitmap(Convert.ToInt32(width), Convert.ToInt32(height)))
            using (var graphics = Graphics.FromImage(newImage))
            {
                graphics.SmoothingMode = SmoothingMode.AntiAlias;
                graphics.InterpolationMode = InterpolationMode.HighQualityBicubic;
                graphics.PixelOffsetMode = PixelOffsetMode.HighQuality;
                graphics.DrawImage(origineel, new Rectangle(0, 0, Convert.ToInt32(width), Convert.ToInt32(height)));
                if (BlobStorageHelper.Exists(thumbnailBestandsnaam))
                {
                    BlobStorageHelper.DeleteIfExists(thumbnailBestandsnaam);
                }
                using (var memorystream = new MemoryStream())
                {
                    newImage.Save(memorystream, ImageFormat.Jpeg);
                    // Reset the stream position to the beginning
                    memorystream.Seek(0, SeekOrigin.Begin);
                    BlobStorageHelper.Upload(memorystream, thumbnailBestandsnaam);
                }
            }
        }


        private string HandleUpload(HttpPostedFileBase uploadedAfbeelding, Afbeelding afbeelding)
        {
            if (uploadedAfbeelding == null || uploadedAfbeelding.ContentLength <= 0) return string.Empty;
            
            var rootFolder = ConfigurationManager.AppSettings["AfbeeldingenFolder"];

            var nieuweBestandsnaam =
                string.Format(
                    "{0}_{1}{2}",
                    Path.GetFileNameWithoutExtension(uploadedAfbeelding.FileName),
                    afbeelding.Id,
                    Path.GetExtension(uploadedAfbeelding.FileName)

src/Website/Areas/Mijn/Views/Afbeelding/Bewerk.cshtml
@model AfbeeldingEditViewModel
@{ ViewBag.Title = string.Format("Bewerk afbeelding {0}", Model.Afbeelding.Omschrijving); }

<h1>@ViewBag.Title</h1>
@using (Html.BeginForm("Bewerk", "Afbeelding", FormMethod.Post, new { name = "FormAfbeelding", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(m => m.Afbeelding.Id)
    @Html.HiddenFor(m => m.Afbeelding.Bestandsnaam)
    @Html.HiddenFor(m => m.Afbeelding.ContentType)

    @Html.Partial("MaakBewerk", Model)
    <p class="clear"></p>
    <a href="@Url.Action("Index")" class="IconKnop">
        <div class="fa fa-arrow-left"></div>
        @Resources.Terug</a>
    <a href="#" onclick="document.FormAfbeelding.submit(); return false;" class="IconKnop">
        <div class="fa fa-save"></div>
        @Resources.Opslaan</a>
 
    <p class="clear"></p>
}

src/Website/Areas/Mijn/Views/Afbeelding/Index.cshtml
@model AfbeeldingIndexViewModel
@{ ViewBag.Title = "Afbeeldingen"; }

<h1>@ViewBag.Title</h1>
<div id="grid">
    @{
        WebGrid wb = new WebGrid(Model.Afbeeldingen, new string[] { "Omschrijving" }, rowsPerPage: 30);
        @wb.GetHtml(
            columns:
                wb.Columns(
                    wb.Column(columnName: "Omschrijving"),
                    wb.Column("Bewerk", " ", format: (item) => { return Html.ActionLink("Bewerk", "Bewerk", new { Id = item.Id }, new { }); }),
                    wb.Column("Verwijder", " ", format: (item) => { return Html.ActionLink("Verwijder", "Verwijder", new { Id = item.Id }, new { OnClick = "return(confirm('Verwijderen, zeker weten?'))" }); })
                )
            );
    }
</div>  
<a href="@Url.Action("Index", "Home", new { Area = "Mijn" })" class="IconKnop">
    <div class="fa fa-arrow-left"></div>
    Beheer</a>
<a href="@Url.Action("Maak")" class="IconKnop">
    <div class="fa fa-file"></div>
    Upload nieuwe afbeelding</a><br />
<br />

src/Website/Areas/Mijn/Views/Afbeelding/Maak.cshtml
@model AfbeeldingEditViewModel
@{ ViewBag.Title = "Upload afbeelding"; }

<h1>@ViewBag.Title</h1>
@using (Html.BeginForm("Maak", "Afbeelding", FormMethod.Post, new { name = "FormAfbeelding", enctype = "multipart/form-data" }))
{
    @Html.Partial("MaakBewerk", Model)
    <p class="clear"></p>
    <a href="@Url.Action("Index")" class="IconKnop">
        <div class="fa fa-arrow-left"></div>
        @Resources.Terug</a>
    <a href="#" onclick="document.FormAfbeelding.submit(); return false;" class="IconKnop">
        <div class="fa fa-save"></div>
        @Resources.Aanmaken</a>
 
    <p class="clear"></p>
}

src/Website/Areas/Mijn/Views/Afbeelding/MaakBewerk.cshtml
@using System.Configuration
@using Prekenweb.Website.Lib.HtmlHelpers
@model AfbeeldingEditViewModel
@Html.ValidationSummary(true)
<div class="ColumnM">
    <div class="field">
        <div class="label">@Html.LabelFor(m => m.Afbeelding.Omschrijving) </div>
        <div class="value">@Html.EditorFor(m => m.Afbeelding.Omschrijving)</div>
        <div class="validator">@Html.ValidationMessageFor(m => m.Afbeelding.Omschrijving)</div>
    </div>
    <div class="field">
        <div class="label">@Html.LabelFor(m => m.Bestand)</div>
        <div class="value">
            @*            <span style="overflow: hidden; width: 140px; display: block;">
                    @Model.Afbeelding.Bestandsnaam
                </span>*@
            <a href="#" class="Knop" onclick="document.getElementById('Bestand').click()">
                Kies @{ if (!string.IsNullOrEmpty(Model.Afbeelding.Bestandsnaam)) { ViewContext.Writer.Write("nieuw "); }}bestand
            </a>
            <div style='height: 0px; width: 0px; overflow: hidden;'>
                <input name="Bestand" id="Bestand" type="file" />
            </div>
        </div>
        <div class="validator">@Html.ValidationMessageFor(m => m.Bestand)</div>
    </div>

</div>
@if (!string.IsNullOrEmpty(Model.Afbeelding.Bestandsnaam))
{
    <div class="ColumnM">
        <div class="field">
            <div class="label">Voorbeeld</div>
            <div class="value">
                <a href="@HtmlHelpers.ContentAbsolute(Url, string.Format("{0}/{1}/{2}", ConfigurationManager.AppSettings["AzureBlobStorageBaseUrl"], ViewBag.AfbeeldingenFolder, Model.Afbeelding.Bestandsnaam))">
                    <img src="@HtmlHelpers.ContentAbsolute(Url, string.Format("{0}/{1}/Thumbnail_{2}.jpg", ConfigurationManager.AppSettings["AzureBlobStorageBaseUrl"], ViewBag.AfbeeldingenFolder, Model.Afbeelding.Id))" />
                </a>

            </div>

        </div>
    </div>
}